export interface EmojiEntry {
  emoji: string;
  label: string;
  keywords: readonly string[];
  categoryId: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: readonly EmojiEntry[];
}

type EmojiSeed = readonly [emoji: string, label: string, keywords?: string];

function category(
  id: string,
  label: string,
  icon: string,
  seeds: readonly EmojiSeed[],
): EmojiCategory {
  return {
    id,
    label,
    icon,
    emojis: seeds.map(([emoji, name, keywords = ""]) => ({
      emoji,
      label: name,
      keywords: keywords.split(" ").filter(Boolean),
      categoryId: id,
    })),
  };
}

/** A deliberately local catalog: native glyphs, no network, no image assets,
 * and useful search words rather than opaque Unicode names. */
export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  category("smileys", "Smileys & emotion", "😀", [
    ["😀", "Grinning face", "happy smile joy"],
    ["😃", "Grinning face with big eyes", "happy smile excited"],
    ["😄", "Grinning squinting face", "happy laugh joy"],
    ["😁", "Beaming face", "happy grin smile"],
    ["😆", "Laughing face", "happy laugh funny"],
    ["😅", "Grinning face with sweat", "relief nervous laugh"],
    ["😂", "Face with tears of joy", "laugh crying funny lol"],
    ["🤣", "Rolling on the floor laughing", "rofl laugh funny lol"],
    ["😊", "Smiling face", "happy blush warm"],
    ["🙂", "Slightly smiling face", "smile friendly"],
    ["🙃", "Upside-down face", "silly sarcasm"],
    ["😉", "Winking face", "wink playful"],
    ["😍", "Heart eyes", "love crush beautiful"],
    ["🥰", "Smiling face with hearts", "love affection"],
    ["😘", "Face blowing a kiss", "kiss love"],
    ["😋", "Face savoring food", "yum tasty tongue"],
    ["😜", "Winking face with tongue", "silly playful"],
    ["🤪", "Zany face", "crazy silly wild"],
    ["🤓", "Nerd face", "geek smart glasses"],
    ["😎", "Face with sunglasses", "cool confident"],
    ["🥳", "Partying face", "party celebrate birthday"],
    ["🤩", "Star-struck", "wow excited amazing"],
    ["🤔", "Thinking face", "think question curious"],
    ["🫡", "Saluting face", "salute respect yes"],
    ["🤗", "Hugging face", "hug support warm"],
    ["🤭", "Face with hand over mouth", "oops giggle secret"],
    ["🤫", "Shushing face", "quiet secret silence"],
    ["🫠", "Melting face", "hot awkward disappear"],
    ["🙄", "Face with rolling eyes", "eyeroll annoyed"],
    ["😬", "Grimacing face", "awkward nervous"],
    ["😌", "Relieved face", "calm peaceful relief"],
    ["🥺", "Pleading face", "please puppy eyes sad"],
    ["😢", "Crying face", "sad tear"],
    ["😭", "Loudly crying face", "sad sob tears"],
    ["😤", "Face with steam", "frustrated triumph"],
    ["😠", "Angry face", "mad annoyed"],
    ["🤬", "Face with symbols on mouth", "swearing angry curse"],
    ["🤯", "Exploding head", "mind blown shocked wow"],
    ["😳", "Flushed face", "embarrassed surprised"],
    ["😱", "Face screaming in fear", "scared shocked horror"],
    ["😮‍💨", "Face exhaling", "sigh relief tired"],
    ["😴", "Sleeping face", "sleep tired night"],
    ["🤒", "Face with thermometer", "sick fever ill"],
    ["🤢", "Nauseated face", "sick gross"],
    ["🤡", "Clown face", "clown silly circus"],
    ["👻", "Ghost", "spooky halloween boo"],
    ["💀", "Skull", "dead skeleton lol"],
    ["💩", "Pile of poo", "poop funny"],
  ]),
  category("people", "People & gestures", "👋", [
    ["👋", "Waving hand", "hello goodbye hi"],
    ["🤚", "Raised back of hand", "stop hand"],
    ["✋", "Raised hand", "stop high five"],
    ["🖖", "Vulcan salute", "spock prosper"],
    ["🫶", "Heart hands", "love support heart"],
    ["👌", "OK hand", "okay perfect good"],
    ["🤌", "Pinched fingers", "italian gesture"],
    ["✌️", "Victory hand", "peace two"],
    ["🤞", "Crossed fingers", "luck hope"],
    ["🤟", "Love-you gesture", "love sign language"],
    ["🤘", "Sign of the horns", "rock metal"],
    ["🤙", "Call me hand", "phone shaka"],
    ["👉", "Backhand index pointing right", "right point"],
    ["👈", "Backhand index pointing left", "left point"],
    ["👆", "Backhand index pointing up", "up point"],
    ["👇", "Backhand index pointing down", "down point"],
    ["👍", "Thumbs up", "yes good approve like"],
    ["👎", "Thumbs down", "no bad disapprove dislike"],
    ["✊", "Raised fist", "power solidarity"],
    ["👊", "Oncoming fist", "fist bump punch"],
    ["🤝", "Handshake", "deal agreement partner"],
    ["👏", "Clapping hands", "applause bravo congrats"],
    ["🙌", "Raising hands", "celebrate hooray praise"],
    ["🙏", "Folded hands", "please thanks pray namaste"],
    ["✍️", "Writing hand", "write note"],
    ["💪", "Flexed biceps", "strong muscle power"],
    ["🧠", "Brain", "smart think mind"],
    ["👀", "Eyes", "look watch see"],
    ["🫂", "People hugging", "hug comfort support"],
    ["💅", "Nail polish", "fabulous beauty sass"],
  ]),
  category("nature", "Animals & nature", "🌿", [
    ["🐶", "Dog face", "pet puppy"],
    ["🐱", "Cat face", "pet kitten"],
    ["🐭", "Mouse face", "animal"],
    ["🐰", "Rabbit face", "bunny animal"],
    ["🦊", "Fox", "animal clever"],
    ["🐻", "Bear", "animal"],
    ["🐼", "Panda", "animal"],
    ["🐨", "Koala", "animal"],
    ["🐯", "Tiger face", "animal"],
    ["🦁", "Lion", "animal king"],
    ["🐸", "Frog", "animal"],
    ["🐵", "Monkey face", "animal"],
    ["🙈", "See-no-evil monkey", "monkey embarrassed"],
    ["🙉", "Hear-no-evil monkey", "monkey listen"],
    ["🙊", "Speak-no-evil monkey", "monkey secret"],
    ["🐧", "Penguin", "animal cold"],
    ["🦉", "Owl", "animal wise night"],
    ["🐝", "Honeybee", "bee insect"],
    ["🦋", "Butterfly", "insect beautiful"],
    ["🐢", "Turtle", "animal slow"],
    ["🐙", "Octopus", "ocean animal"],
    ["🐬", "Dolphin", "ocean animal"],
    ["🐳", "Spouting whale", "ocean animal"],
    ["🌸", "Cherry blossom", "flower spring pink"],
    ["🌹", "Rose", "flower love"],
    ["🌻", "Sunflower", "flower summer"],
    ["🌱", "Seedling", "plant grow new"],
    ["🌿", "Herb", "plant leaf green"],
    ["🍀", "Four leaf clover", "luck plant"],
    ["🌙", "Crescent moon", "night sleep"],
    ["⭐", "Star", "favorite night"],
    ["✨", "Sparkles", "magic shine new"],
    ["☀️", "Sun", "weather bright summer"],
    ["🌈", "Rainbow", "weather pride color"],
    ["🔥", "Fire", "hot lit flame"],
  ]),
  category("food", "Food & drink", "🍕", [
    ["🍎", "Red apple", "fruit food"],
    ["🍊", "Tangerine", "orange fruit food"],
    ["🍋", "Lemon", "fruit sour"],
    ["🍌", "Banana", "fruit food"],
    ["🍉", "Watermelon", "fruit summer"],
    ["🍇", "Grapes", "fruit food"],
    ["🍓", "Strawberry", "fruit berry"],
    ["🫐", "Blueberries", "fruit berry"],
    ["🍒", "Cherries", "fruit food"],
    ["🥭", "Mango", "fruit tropical"],
    ["🍍", "Pineapple", "fruit tropical"],
    ["🥑", "Avocado", "fruit food"],
    ["🥦", "Broccoli", "vegetable healthy"],
    ["🌶️", "Hot pepper", "spicy chili"],
    ["🥐", "Croissant", "bread breakfast"],
    ["🍞", "Bread", "food toast"],
    ["🧀", "Cheese wedge", "food"],
    ["🍳", "Cooking", "egg breakfast"],
    ["🥞", "Pancakes", "breakfast food"],
    ["🍔", "Hamburger", "burger food"],
    ["🍟", "French fries", "food potato"],
    ["🍕", "Pizza", "food slice"],
    ["🌮", "Taco", "food mexican"],
    ["🍜", "Steaming bowl", "noodles soup ramen"],
    ["🍣", "Sushi", "food japanese"],
    ["🍩", "Doughnut", "donut sweet"],
    ["🍪", "Cookie", "sweet biscuit"],
    ["🎂", "Birthday cake", "cake celebrate"],
    ["🍫", "Chocolate bar", "sweet candy"],
    ["🍿", "Popcorn", "movie snack"],
    ["☕", "Hot beverage", "coffee tea morning"],
    ["🍵", "Teacup", "tea drink"],
    ["🍺", "Beer mug", "drink cheers"],
    ["🍷", "Wine glass", "drink cheers"],
  ]),
  category("activities", "Activities", "🥊", [
    ["⚽", "Soccer ball", "football sport"],
    ["🏀", "Basketball", "sport ball"],
    ["🏈", "American football", "sport ball"],
    ["⚾", "Baseball", "sport ball"],
    ["🎾", "Tennis", "sport ball"],
    ["🏐", "Volleyball", "sport ball"],
    ["🎱", "Pool 8 ball", "billiards game"],
    ["🏓", "Ping pong", "table tennis sport"],
    ["🥊", "Boxing glove", "champ fight sport"],
    ["🥋", "Martial arts uniform", "karate judo"],
    ["🎯", "Bullseye", "target goal"],
    ["🏋️", "Person lifting weights", "gym strength"],
    ["🧘", "Person in lotus position", "meditate calm yoga"],
    ["🎮", "Video game", "controller gaming"],
    ["🎲", "Game die", "dice game luck"],
    ["🧩", "Puzzle piece", "puzzle solve"],
    ["🎨", "Artist palette", "art paint creative"],
    ["🎭", "Performing arts", "theater drama"],
    ["🎤", "Microphone", "sing music"],
    ["🎧", "Headphone", "music listen"],
    ["🎸", "Guitar", "music rock"],
    ["🥁", "Drum", "music beat"],
    ["🎬", "Clapper board", "movie film action"],
    ["📸", "Camera with flash", "photo picture"],
    ["🏆", "Trophy", "winner award champion"],
    ["🥇", "Gold medal", "winner first award"],
  ]),
  category("travel", "Travel & places", "🚀", [
    ["🚗", "Automobile", "car travel"],
    ["🚕", "Taxi", "cab car"],
    ["🚌", "Bus", "travel transport"],
    ["🏎️", "Racing car", "fast sport"],
    ["🚑", "Ambulance", "emergency medical"],
    ["🚒", "Fire engine", "emergency truck"],
    ["🚲", "Bicycle", "bike cycle"],
    ["🏍️", "Motorcycle", "bike travel"],
    ["✈️", "Airplane", "flight travel"],
    ["🚀", "Rocket", "space launch fast"],
    ["🛸", "Flying saucer", "ufo alien space"],
    ["🚁", "Helicopter", "flight travel"],
    ["⛵", "Sailboat", "ship sea travel"],
    ["🚢", "Ship", "boat sea travel"],
    ["🚆", "Train", "rail travel"],
    ["🚇", "Metro", "subway train"],
    ["🗺️", "World map", "travel explore"],
    ["🧭", "Compass", "direction explore"],
    ["🏠", "House", "home building"],
    ["🏢", "Office building", "work city"],
    ["🏰", "Castle", "building travel"],
    ["⛺", "Tent", "camping outdoors"],
    ["🏖️", "Beach with umbrella", "holiday sea"],
    ["🏔️", "Snow-capped mountain", "nature travel"],
    ["🌋", "Volcano", "nature mountain"],
    ["🌍", "Globe showing Europe and Africa", "earth world planet"],
  ]),
  category("objects", "Objects", "💡", [
    ["⌚", "Watch", "time clock"],
    ["📱", "Mobile phone", "smartphone device"],
    ["💻", "Laptop", "computer code work"],
    ["⌨️", "Keyboard", "computer type"],
    ["🖥️", "Desktop computer", "monitor work"],
    ["🖱️", "Computer mouse", "click device"],
    ["💾", "Floppy disk", "save storage"],
    ["📷", "Camera", "photo picture"],
    ["🎥", "Movie camera", "video film"],
    ["📞", "Telephone receiver", "phone call"],
    ["💡", "Light bulb", "idea bright"],
    ["📚", "Books", "read study library"],
    ["📖", "Open book", "read story"],
    ["📝", "Memo", "write note"],
    ["✏️", "Pencil", "write edit"],
    ["📌", "Pushpin", "pin location"],
    ["📎", "Paperclip", "attach office"],
    ["🔗", "Link", "chain url"],
    ["🧰", "Toolbox", "tools work"],
    ["🔧", "Wrench", "tool fix"],
    ["🔨", "Hammer", "tool build"],
    ["⚙️", "Gear", "settings tool"],
    ["🧲", "Magnet", "attract"],
    ["🔬", "Microscope", "science research"],
    ["🔭", "Telescope", "space science"],
    ["💊", "Pill", "medicine health"],
    ["🩹", "Adhesive bandage", "heal health"],
    ["🔑", "Key", "lock access"],
    ["🎁", "Wrapped gift", "present birthday"],
    ["🎈", "Balloon", "party celebrate"],
    ["💰", "Money bag", "cash rich"],
    ["💎", "Gem stone", "diamond valuable"],
  ]),
  category("symbols", "Symbols", "🖤", [
    ["❤️", "Red heart", "love heart"],
    ["🧡", "Orange heart", "love heart"],
    ["💛", "Yellow heart", "love heart"],
    ["💚", "Green heart", "love heart"],
    ["💙", "Blue heart", "love heart"],
    ["💜", "Purple heart", "love heart"],
    ["🖤", "Black heart", "love heart dark"],
    ["🤍", "White heart", "love heart"],
    ["🤎", "Brown heart", "love heart"],
    ["💔", "Broken heart", "sad love"],
    ["💕", "Two hearts", "love affection"],
    ["💖", "Sparkling heart", "love shine"],
    ["💯", "Hundred points", "perfect score agree"],
    ["✅", "Check mark button", "yes done correct"],
    ["❌", "Cross mark", "no wrong delete"],
    ["❗", "Exclamation mark", "important alert"],
    ["❓", "Question mark", "question help"],
    ["‼️", "Double exclamation mark", "important alert"],
    ["⁉️", "Exclamation question mark", "surprised question"],
    ["⚠️", "Warning", "alert caution"],
    ["🚫", "Prohibited", "stop banned no"],
    ["♾️", "Infinity", "forever endless"],
    ["☮️", "Peace symbol", "peace"],
    ["🔴", "Red circle", "color dot"],
    ["🟠", "Orange circle", "color dot"],
    ["🟡", "Yellow circle", "color dot"],
    ["🟢", "Green circle", "color dot"],
    ["🔵", "Blue circle", "color dot"],
    ["🟣", "Purple circle", "color dot"],
    ["⚫", "Black circle", "color dot"],
    ["⚪", "White circle", "color dot"],
    ["🏁", "Chequered flag", "finish race done"],
    ["🚩", "Triangular flag", "warning goal red flag"],
  ]),
];

export const ALL_EMOJIS: readonly EmojiEntry[] = EMOJI_CATEGORIES.flatMap(
  (item) => item.emojis,
);

export const EMOJI_BY_CHARACTER = new Map(
  ALL_EMOJIS.map((entry) => [entry.emoji, entry] as const),
);

export function emojiSearchText(entry: EmojiEntry): string {
  return `${entry.emoji} ${entry.label} ${entry.keywords.join(" ")}`.toLowerCase();
}
